base_app/base_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('treasurehunt.urls'))
]

base_app/treasurehunt/urls.py
from django.urls import path
from . import views
app_name = 'treasurehunt'

urlpatterns = [
    path('', views.user_login, name='index'),
    path('question/', views.question, name="question"),
    path('logout/', views.user_logout, name="logout"),
    # path('login/', views.user_login, name='login'),
    path('leaderboard/', views.leaderboard, name='leaderboard')
]

base_app/treasurehunt/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.models import BaseUserManager
from django import forms
from django.core import validators
from datetime import date

# Create your models here.


class UserProfileManager(BaseUserManager):
    """Manager for user profiles"""
    def create_user(self, email, name, password=None):
        """Create a new user profile"""
        if not email:
            raise ValueError('Users Must have an email address')

        email = self.normalize_email(email)
        user = self.model(email=email, name=name)

        user.set_password(password)
        # Not necessary to write anything inside brackets
        user.save(using=self._db)

        return user

    def create_superuser(self, email, name, password):
        """Create new superuser with given details"""
        user = self.create_user(email, name, password)

        user.is_superuser = True
        user.is_staff = True
        user.save(using=self._db)
        return user


class UserProfile(AbstractBaseUser, PermissionsMixin):
    """Database Model for users in system"""

    email = models.EmailField(max_length=255, unique=True)
    name = models.CharField(max_length=255)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    # Custom Manager To handle users with email field as the main field
    # instead of username
    objects = UserProfileManager()
    # Done to handle Django Admin
    USERNAME_FIELD = 'email'
    # Required Field can include more fields
    REQUIRED_FIELDS = ['name']

    def get_full_name(self):
        """Retrieve Full Name"""
        return self.name

    def get_short_name(self):
        return self.name

    def __str__(self):
        """Return String representation of user"""
        return self.name


# Create your models here.
class Score(models.Model):

    user = models.OneToOneField(UserProfile, on_delete=models.CASCADE)
    score = models.PositiveIntegerField(default=0)
    last_answer = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.email


class Answer(models.Model):
    answer = models.CharField(max_length=255)


class AnswerChecker(models.Model):
    index = models.PositiveIntegerField(default=0, unique=True)
    answer = models.CharField(max_length=255)

    def __str__(self):
        return self.answer

    def ans_value(self):
        return self.answer

base_app/treasurehunt/forms.py
from django import forms
from . import models


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'placeholder': 'Enter the Password'}))
    confirm_password = forms.CharField(widget=forms.PasswordInput(
        attrs={'placeholder': 'Reenter the password'}))

    class Meta():
        model = models.UserProfile
        fields = ('email', 'password', 'confirm_password')


class Answer(forms.ModelForm):
    answer = forms.CharField()

    class Meta():
        model = models.Answer
        fields = ('answer', )

base_app/treasurehunt/views.py
from django.shortcuts import render
from . import forms
# Create your views here.
from treasurehunt import models
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from datetime import datetime
from django.contrib import messages

# def index(request):
#     return render(request, 'treasurehunt/index.html')

# def register(request):
#     if request.user.is_authenticated:
#         return HttpResponseRedirect(reverse('treasurehunt:question'))
#     registered = False

#     if request.method == 'POST':
#         user_form = forms.UserForm(data=request.POST)
#         if user_form.is_valid():
#             passmain = user_form.cleaned_data['password']
#             passverify = user_form.cleaned_data['confirm_password']
#             if passmain == passverify:
#                 user = user_form.save()
#                 user.set_password(user.password)
#                 user.save()

#                 score = models.Score()
#                 score.user = user
#                 score.save()

#                 registered = True
#             else:
#                 return HttpResponse("Password Don't Match")
#         else:
#             print(user_form.errors)
#     else:
#         user_form = forms.UserForm()

#     return render(request, 'treasurehunt/signup.html', {
#         'user_form': user_form,
#         'registered': registered
#     })


def user_login(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('treasurehunt:question'))
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(email=email, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('treasurehunt:question'))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            messages.warning(request, 'Wrong Email ID or Password')
            return render(request, 'treasurehunt/index.html', {'flag': 1})
    else:
        return render(request, 'treasurehunt/index.html', {'flag': 1})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('treasurehunt:index'))


@login_required
def question(request):

    question_fixed = [
        '4LcGlbjua3',
    ]

    current_user = request.user
    sc = models.Score.objects.get(user__exact=current_user)
    if sc.score == 1:
        return render(request, 'treasurehunt/end.html')
    else:
        if request.method == 'POST' and sc.score != 1:
            ans_fixed = models.AnswerChecker.objects.get(index__exact=sc.score)
            question_form = forms.Answer(data=request.POST)
            if question_form.is_valid():
                ans = question_form.cleaned_data['answer']
                if ans.lower() == ans_fixed.ans_value():
                    sc.score = sc.score + 1
                    sc.save()
                else:
                    return render(
                        request, 'treasurehunt/question.html', {
                            'flag': 0,
                            'question_form': question_form,
                            'score': sc.score,
                            'question_fixed': question_fixed[sc.score],
                        })
            else:
                return render(
                    request, 'treasurehunt/question.html', {
                        'flag': 0,
                        'question_form': question_form,
                        'score': sc.score,
                        'question_fixed': question_fixed[sc.score],
                    })
        elif sc.score == 1:
            return render(request, 'treasurehunt/end.html')
        else:
            question_form = forms.Answer()
        return render(
            request, 'treasurehunt/question.html', {
                'flag': 0,
                'question_form': question_form,
                'score': sc.score,
                'question_fixed': question_fixed[sc.score],
            })


def leaderboard(request):
    leader = models.Score.objects.all().order_by('-score', 'last_answer')
    if len(leader) >= 30:
        user_name = []
        for x in leader[:30]:
            user_name.append((x.user.name, x.score, x.last_answer))
        return render(request, 'treasurehunt/leaderboard.html', {
            'flag': 0,
            'user_name': user_name,
        })
    else:
        user_name = []
        for x in leader:
            user_name.append((x.user.name, x.score, x.last_answer))
        return render(request, 'treasurehunt/leaderboard.html', {
            'user_name': user_name,
        })


#t = Score.objects.all().order_by('-score')
# t[0].user.username

base_app/treasurehunt/templates/treasurehunt/base.html
<!DOCTYPE html>
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Sasta Farewell 20'</title>
    <link rel="icon" href="{% static 'images/favi.png'%}" type="image/png" sizes="16x16">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'styles/style.css'%}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>


<body>
    <nav class="navbar navbar-default navbar-expand-lg navbar-light">
        <div class="container">
            <div class="navbar-header d-flex col">
                <a href="{% url 'treasurehunt:index' %}" class="navbar-brand"><img src="{% static 'images/logo.jpg'%}"
                        height=25vh width=80vw></img></a>
                <button type="button" data-target="#navbarCollapse" data-toggle="collapse"
                    class="navbar-toggle navbar-toggler ml-auto">
                    <span class="navbar-toggler-icon"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div id="navbarCollapse" class="collapse navbar-collapse justify-content-start">
                <ul class="nav navbar-nav">
                    <li class="nav-item active"><a href="{% url 'treasurehunt:index' %}" class="nav-link">Home</a></li>
                    <li class="nav-item"><a href="{% static 'files/Rules.pdf'%}" target="_blank"
                            rel="noopener noreferrer">Rules</a></li>
                    <li class="nav-item"><a href="{% url 'treasurehunt:leaderboard' %}">Leaderboard</a></li>
                </ul>
                {% if user.is_authenticated %}
                <ul class="nav navbar-nav navbar-right ml-auto">
                    <li class="nav-item"><a href="{% url 'treasurehunt:question' %}">Question</a></li>
                    <li class="nav-item"><a href="#" style="text-transform: none;">Logged in as : {{user.name}}
                        </a></li>
                    <li class="nav-item"><a href="{% url 'treasurehunt:logout' %}">Logout</a></li>
                </ul>
                {% elif flag == 1 %}
                <ul class="nav navbar-nav navbar-right ml-auto">
                    <li class="nav-item dropdown">
                        <a data-toggle="dropdown" class="nav-link dropdown-toggle" href="#"><i class="fa fa-user-o"></i>
                            Sign In</a>
                        <ul class="dropdown-menu">
                            <li>
                                <form class="form-inline login-form" method="post"
                                    action="{% url 'treasurehunt:index' %}">
                                    {% csrf_token %}
                                    <div class="input-group">
                                        <span class="input-group-addon"><i class="fa fa-user"></i></span>
                                        <input type="email" name="email" class="form-control" placeholder="Email"
                                            required>
                                    </div>
                                    <div class="input-group">
                                        <span class="input-group-addon"><i class="fa fa-lock"></i></span>
                                        <input type="password" name="password" class="form-control"
                                            placeholder="Password" required>
                                    </div>
                                    <button type="submit" class="btn btn-primary">Login</button>
                                </form>
                                <br>
                                {% if messages %}

                                {% for message in messages %}
                                <div class="alert alert-danger alert-dismissible" role="alert">
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                    {{ message }}
                                </div>
                                {% endfor %}

                                {% endif %}
                            </li>

                        </ul>
                    </li>
                </ul>
                {% endif %}

            </div>
        </div>
    </nav>
    <!-- End Navbar Section -->
    {% block content %}
    {% endblock content %}

    {% if flag == 1 %}
    {% endif %}
</body>

</html>

base_app/treasurehunt/templates/treasurehunt/end.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Brain Rush 2020 | A Project Sahara Initiative</title>
	<link rel="icon" href="{% static 'images/pst.png'%}" type="image/png" sizes="16x16">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<style>
	.img-thumbnail {
		height: 100vh;
		width: 100vw;
	}
</style>

<body>
	<img src="{% static 'images/end.png'%}" alt="RespImg" class="img-thumbnail">
</body>

</html>

base_app/treasurehunt/templates/treasurehunt/index.html
{% extends "treasurehunt/base.html" %}
{% block content %}
{% load static %}

{% endblock content %}

base_app/treasurehunt/templates/treasurehunt/leaderboard.html
{% extends "treasurehunt/base.html" %}
{% block content %}
{% load static %}
<br><br><br><br><br>
<div class="container leader" style="background : white;">
    <center>
        <strong>
            <h2>Leaderboard</h2>
        </strong>
    </center>
    <center>
        <h5>
            <table style="border: 2px solid black;">
                <tr>
                    <th style="border: 2px solid black;padding: 15px;">Email</th>
                    <th style="border: 2px solid black;padding: 15px;">Score</th>
                    <th style="border: 2px solid black;padding: 15px;">Last Answer Submitted</th>
                </tr>
                {% for x,y,z in user_name  %}
                <tr>
                    <td style="border: 2px solid black; text-align :center;padding: 15px;">{{x}}</td>
                    <td style="border: 2px solid black;text-align :center;padding: 15px;">{{y}}</td>
                    <td style="border: 2px solid black;text-align :center;padding: 15px;">{{z}}</td>
                </tr>
                {% endfor %}

            </table>
        </h5>
    </center>
</div>
{% endblock content %}

base_app/treasurehunt/templates/treasurehunt/question.html
{% extends "treasurehunt/base.html" %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}
<!-- End Navbar Section -->
<br><br><br><br><br>
<div class="container">
	<img src="{% static 'images/'%}{{question_fixed}}.png" type="image/png" alt="RespImg" class="img-thumbnail">
	<form method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		{{question_form|crispy}}
		<button type="submit" class="btn btn-success mtop2">Submit</button>
	</form>
</div>
{% endblock content %}